export const BASE_URL = "https://waba-v2.360dialog.io";
export const SESSION_TIMEOUT = 10 * 60 * 1000;

export const STATES = {
  MAIN_MENU: "main_menu",
  QUOTE_CATEGORY: "quote_category",
  HEALTH_USER_TYPE: "health_user_type",
  HEALTH_AGE: "health_age",
  HEALTH_STATE: "health_state",
  HEALTH_CONDITIONS: "health_conditions",
  HEALTH_PLANS: "health_plans",
  AUTO_TYPE: "auto_type",
  AUTO_BRAND: "auto_brand",
  AUTO_MODEL: "auto_model",
  AUTO_YEAR: "auto_year",
  AUTO_VALUE: "auto_value",
  AUTO_PLANS: "auto_plans",
  DEVICE_TYPE: "device_type",
  DEVICE_BRAND: "device_brand",
  DEVICE_MODEL: "device_model",
  DEVICE_CONDITION: "device_condition",
  DEVICE_VALUE: "device_value",
  DEVICE_PLANS: "device_plans",
  LIFE_AGE: "life_age",
  LIFE_DEPENDENTS: "life_dependents",
  LIFE_SUM: "life_sum",
  LIFE_CONDITIONS: "life_conditions",
  LIFE_PLANS: "life_plans",
  PROPERTY_TYPE: "property_type",
  PROPERTY_STATE: "property_state",
  PROPERTY_VALUE: "property_value",
  PROPERTY_COVERAGE: "property_coverage",
  PROPERTY_PLANS: "property_plans",
  SALARY_AMOUNT: "salary_amount",
  SALARY_EMPLOYMENT: "salary_employment",
  SALARY_COVERAGE: "salary_coverage",
  SALARY_PLANS: "salary_plans",
  CREDIT_AMOUNT: "credit_amount",
  CREDIT_DURATION: "credit_duration",
  CREDIT_TYPE: "credit_type",
  CREDIT_PLANS: "credit_plans",
  PAYMENT_METHOD: "payment_method",
  PAYMENT_CONFIRMATION: "payment_confirmation",
  POLICY_LOOKUP: "policy_lookup",
  POLICY_OPTIONS: "policy_options",
  CLAIMS_MENU: "claims_menu",
  CLAIM_TYPE: "claim_type",
  CLAIM_DESCRIPTION: "claim_description",
  CLAIM_LOCATION: "claim_location",
  CLAIM_DOCUMENTS: "claim_documents",
  CLAIM_TRACKING: "claim_tracking",
  LEARN_PRODUCTS: "learn_products",
  PRODUCT_DETAIL: "product_detail",
  FAQ_CATEGORY: "faq_category",
  AGENT_CONNECT: "agent_connect",
};
