export const HEALTH_PLANS = [
  // Basic Plans (Monthly)
  {
    id: 1,
    title: "Chuks Basic",
    cost: 10,
    period: "month",
    currency: "NGN",
    category: "basic",
    description:
      "Essential healthcare services including outpatient care, inpatient services (up to 18 days/year), diagnostics, minor surgeries (up to ₦60,000), emergency care, telemedicine, and wellness checks. Annual medical limit: ₦200,000",
    annualLimit: "₦200,000",
    detailedCoverage: [
      "*Outpatient Services:* General and specialist consultations, prescribed drugs, laboratory tests, X-rays",
      "*Inpatient Services:* General ward admission (up to 18 days/year), feeding up to ₦1,500/day",
      "*Dental Services:* Pain management, simple tooth extraction (up to 2 teeth/year)",
      "*Optical Services:* Conjunctivitis treatment, foreign body removal, specialist consultation",
      "*Surgeries:* Minor/intermediate (up to ₦60,000), Major (up to ₦100,000)",
      "*Emergency Care:* Stabilization, evacuation, trauma management (up to ₦60,000/year)",
      "*Mental Health:* Psychiatric consultation and treatment (up to 8 weeks)",
      "*Telemedicine:* Teleconsultation and telepharmacy services",
      "*Wellness Checks:* Blood pressure, BMI, eye screening, weight, height",
    ],
  },
  {
    id: 2,
    title: "Chuks Plus",
    cost: 7000,
    period: "month",
    currency: "NGN",
    category: "basic",
    description:
      "Comprehensive plan covering primary, secondary, and tertiary healthcare services. Includes specialist consultations, childhood immunizations, advanced diagnostics, and hospital admissions. Annual medical limit: ₦400,000",
    annualLimit: "₦400,000",
    detailedCoverage: [
      "*Primary Healthcare:* Outpatient consultations, routine lab tests, childhood immunizations",
      "*Treatment Coverage:* Malaria, infections, diarrhea, pneumonia, anemia",
      "*Surgical Procedures:* Minor surgical procedures and wound care",
      "*Specialized Care:* HIV/AIDS counseling, mental health care, pediatric care",
      "*Maternity Care:* Routine obstetrics and gynecology services",
      "*Secondary Healthcare:* Hospital admissions, specialist referrals, physiotherapy",
      "*Tertiary Healthcare:* Advanced medical and surgical services",
      "*Dental Services:* Scaling, polishing, and comprehensive dental care",
    ],
  },
  {
    id: 3,
    title: "Chuks Senior Basic",
    cost: 35000,
    period: "month",
    currency: "NGN",
    category: "basic",
    description:
      "Specialized geriatric care for ages 60-89. Covers pre-existing conditions (arthritis, hypertension, diabetes), preventive wellness checks, eye glasses provision, dental care, physiotherapy, and chronic illness support",
    detailedCoverage: [
      "*Pre-existing Conditions:* Arthritis, hypertension, diabetes management and treatment",
      "*Geriatric Care:* Specialized elderly healthcare services and consultations",
      "*Preventive Care:* Regular wellness checks, health screenings, and monitoring",
      "*Vision Care:* Eye glasses provision and optical services",
      "*Dental Services:* Comprehensive dental care and treatments",
      "*Physiotherapy:* Rehabilitation and physical therapy sessions",
      "*Chronic Illness Support:* Ongoing management and medication coverage",
      "*Emergency Services:* 24/7 emergency medical care and stabilization",
    ],
  },
  {
    id: 4,
    title: "Chuks Senior Plus",
    cost: 47000,
    period: "month",
    currency: "NGN",
    category: "basic",
    description:
      "Premium senior coverage with comprehensive geriatric care, advanced investigations (CT/MRI), intensive care services, 3 square meals, and extensive chronic illness management for ages 60-89",
    detailedCoverage: [
      "*Advanced Diagnostics:* CT scans, MRI, and comprehensive medical investigations",
      "*Intensive Care:* ICU services and critical care management",
      "*Meal Services:* 3 square meals daily during hospital stays",
      "*Comprehensive Geriatric Care:* Specialized elderly medical services",
      "*Chronic Disease Management:* Extensive support for long-term conditions",
      "*Specialist Consultations:* Access to geriatricians and specialists",
      "*Emergency Care:* Priority emergency services and ambulance coverage",
      "*Rehabilitation Services:* Physical therapy and recovery programs",
    ],
  },
  // Diaspora Plans (USD)
  {
    id: 5,
    title: "Chuks Basic Diaspora",
    cost: 62,
    period: "year",
    currency: "USD",
    category: "diaspora",
    description:
      "Comprehensive coverage for diaspora including inpatient, outpatient, dental, optical, emergency care, surgeries, rehabilitative services, HIV/AIDS support, and wellness checks",
    detailedCoverage: [
      "*Inpatient Services:* Hospital admissions and ward accommodations",
      "*Outpatient Care:* General and specialist consultations",
      "*Dental Services:* Routine dental care and treatments",
      "*Optical Services:* Eye care and vision correction",
      "*Emergency Care:* 24/7 emergency medical services",
      "*Surgical Procedures:* Minor and intermediate surgeries",
      "*Rehabilitative Services:* Physical therapy and recovery programs",
      "*HIV/AIDS Support:* Counseling and treatment services",
      "*Wellness Checks:* Preventive health screenings and monitoring",
    ],
  },
  {
    id: 6,
    title: "Chuks Plus Diaspora",
    cost: 78,
    period: "year",
    currency: "USD",
    category: "diaspora",
    description:
      "Enhanced diaspora plan with primary, secondary, and tertiary care coverage. Includes maternity care, immunizations, specialist services, and telemedicine. Annual limit: ₦500,000",
    annualLimit: "₦500,000",
    detailedCoverage: [
      "*Primary Healthcare:* Basic medical consultations and treatments",
      "*Secondary Healthcare:* Specialist referrals and hospital services",
      "*Tertiary Healthcare:* Advanced medical and surgical procedures",
      "*Maternity Care:* Prenatal, delivery, and postnatal services",
      "*Immunizations:* Childhood and adult vaccination programs",
      "*Specialist Services:* Access to medical specialists and consultants",
      "*Telemedicine:* Remote consultations and digital health services",
      "*Diagnostic Services:* Laboratory tests and medical imaging",
    ],
  },
  {
    id: 7,
    title: "Chuks Superior Diaspora",
    cost: 92,
    period: "year",
    currency: "USD",
    category: "diaspora",
    description:
      "Comprehensive diaspora package with chronic disease management, maternity care, cancer care (up to ₦300,000), fertility services, advanced diagnostics, and wellness services. Annual limit: ₦1,000,000",
    annualLimit: "₦1,000,000",
    detailedCoverage: [
      "*Chronic Disease Management:* Long-term condition monitoring and treatment",
      "*Maternity Care:* Complete pregnancy and childbirth coverage",
      "*Cancer Care:* Oncology treatments up to ₦300,000",
      "*Fertility Services:* Reproductive health and fertility treatments",
      "*Advanced Diagnostics:* CT scans, MRI, and specialized tests",
      "*Wellness Services:* Preventive care and health promotion programs",
      "*Specialist Care:* Access to medical specialists and consultants",
      "*Emergency Services:* Comprehensive emergency medical coverage",
    ],
  },
  {
    id: 8,
    title: "Chuks Senior Diaspora",
    cost: 300,
    period: "year",
    currency: "USD",
    category: "diaspora",
    description:
      "Specialized senior diaspora care with comprehensive chronic condition management, surgery coverage (up to ₦500,000), dialysis sessions, and extensive wellness services. Annual limit: ₦2,500,000",
    annualLimit: "₦2,500,000",
    detailedCoverage: [
      "*Chronic Condition Management:* Comprehensive care for long-term illnesses",
      "*Surgery Coverage:* Surgical procedures up to ₦500,000",
      "*Dialysis Sessions:* Kidney dialysis treatments and support",
      "*Geriatric Care:* Specialized elderly healthcare services",
      "*Wellness Services:* Extensive preventive care and health monitoring",
      "*Emergency Care:* Priority emergency medical services",
      "*Specialist Consultations:* Access to geriatricians and specialists",
      "*Rehabilitation Services:* Physical therapy and recovery programs",
    ],
  },
  {
    id: 9,
    title: "Chuks Ruby",
    cost: 400,
    period: "year",
    currency: "USD",
    category: "diaspora",
    description:
      "Extensive diaspora coverage with maternity care, cancer treatment (up to ₦300,000), 15 physiotherapy sessions, comprehensive dental care, eye surgery, and behavioral health support. Annual limit: ₦4,000,000",
    annualLimit: "₦4,000,000",
    detailedCoverage: [
      "*Maternity Care:* Complete pregnancy, delivery, and postnatal services",
      "*Cancer Treatment:* Oncology care and treatments up to ₦300,000",
      "*Physiotherapy:* 15 sessions of physical therapy and rehabilitation",
      "*Comprehensive Dental Care:* Full dental treatments and procedures",
      "*Eye Surgery:* Optical surgical procedures and treatments",
      "*Behavioral Health Support:* Mental health counseling and therapy",
      "*Emergency Services:* 24/7 emergency medical care",
      "*Specialist Care:* Access to medical specialists and consultants",
    ],
  },
  {
    id: 10,
    title: "Chuks Gold",
    cost: 565,
    period: "year",
    currency: "USD",
    category: "diaspora",
    description:
      "Enhanced diaspora plan with all surgeries including laparoscopic (up to ₦1,000,000), cancer care, fertility investigations, extensive dental coverage, gym access (7 sessions/month), and spa services",
    detailedCoverage: [
      "*All Surgeries:* Including laparoscopic procedures up to ₦1,000,000",
      "*Cancer Care:* Comprehensive oncology treatments and support",
      "*Fertility Investigations:* Reproductive health assessments and treatments",
      "*Extensive Dental Coverage:* Complete dental care and procedures",
      "*Gym Access:* 7 fitness sessions per month for wellness",
      "*Spa Services:* Wellness and relaxation therapy sessions",
      "*Advanced Diagnostics:* Comprehensive medical imaging and tests",
      "*Specialist Care:* Premium access to medical specialists",
    ],
  },
  {
    id: 11,
    title: "Chuks Diamond",
    cost: 825,
    period: "year",
    currency: "USD",
    category: "diaspora",
    description:
      "Most comprehensive diaspora plan with global treatment coverage, advanced diagnostics (CT/MRI), extensive specialist services, cancer therapy, dialysis, telemedicine, and mental health support. Annual limit: ₦7,000,000",
    annualLimit: "₦7,000,000",
    detailedCoverage: [
      "*Global Treatment Coverage:* Worldwide medical care and services",
      "*Advanced Diagnostics:* CT scans, MRI, and specialized imaging",
      "*Extensive Specialist Services:* Premium access to all medical specialists",
      "*Cancer Therapy:* Comprehensive oncology treatments and care",
      "*Dialysis Services:* Kidney dialysis treatments and support",
      "*Telemedicine:* Remote consultations and digital health services",
      "*Mental Health Support:* Psychiatric care and counseling services",
      "*Emergency Care:* Priority global emergency medical services",
    ],
  },
  {
    id: 12,
    title: "Chuks Travel Plan",
    cost: 425,
    period: "year",
    currency: "USD",
    category: "diaspora",
    description:
      "Short-term emergency travel insurance for diaspora travelers. Covers urgent healthcare needs, outpatient/inpatient care, maternity, chronic disease support, and emergency services for 4-6 weeks",
    detailedCoverage: [
      "*Emergency Healthcare:* Urgent medical care during travel (4-6 weeks)",
      "*Outpatient Care:* Medical consultations and treatments",
      "*Inpatient Services:* Hospital admissions and care",
      "*Maternity Coverage:* Emergency pregnancy and childbirth care",
      "*Chronic Disease Support:* Ongoing condition management during travel",
      "*Emergency Services:* 24/7 emergency medical assistance",
      "*Medical Evacuation:* Emergency transportation to medical facilities",
      "*Travel Health Support:* Health assistance and guidance while traveling",
    ],
  },
  // HDPTC Plans (Naira)
  {
    id: 13,
    title: "Chuks Basic HDPTC",
    cost: 46600,
    period: "year",
    currency: "NGN",
    category: "hdptc",
    description:
      "High Deductible Plan with tax benefits, Health Savings Account options, essential healthcare coverage, and preventive care services",
    detailedCoverage: [
      "*Tax Benefits:* Eligible for tax deductions and savings",
      "*Health Savings Account:* HSA options for medical expenses",
      "*Essential Healthcare:* Basic medical coverage and services",
      "*Preventive Care:* Health screenings and wellness checks",
      "*High Deductible Structure:* Lower premiums with higher deductibles",
      "*Outpatient Services:* General medical consultations",
      "*Emergency Care:* Basic emergency medical services",
      "*Prescription Coverage:* Essential medication coverage",
    ],
  },
  {
    id: 14,
    title: "Chuks Plus HDPTC",
    cost: 56500,
    period: "year",
    currency: "NGN",
    category: "hdptc",
    description:
      "Enhanced HDPTC with lower deductibles, expanded preventive care coverage, specialist consultations, and comprehensive diagnostic services",
    detailedCoverage: [
      "*Lower Deductibles:* Reduced out-of-pocket costs before coverage",
      "*Expanded Preventive Care:* Comprehensive health screenings and wellness",
      "*Specialist Consultations:* Access to medical specialists",
      "*Comprehensive Diagnostics:* Laboratory tests and medical imaging",
      "*Enhanced Coverage:* Improved benefits over basic HDPTC",
      "*Tax Advantages:* Eligible for health savings account benefits",
      "*Prescription Coverage:* Enhanced medication benefits",
      "*Emergency Services:* Comprehensive emergency medical care",
    ],
  },
  {
    id: 15,
    title: "Chuks Senior HDPTC",
    cost: 275000,
    period: "year",
    currency: "NGN",
    category: "hdptc",
    description:
      "Senior-focused HDPTC with specialized geriatric care, chronic disease management, advanced investigations, and comprehensive elderly care services",
    detailedCoverage: [
      "*Specialized Geriatric Care:* Elderly-focused medical services",
      "*Chronic Disease Management:* Long-term condition care and monitoring",
      "*Advanced Investigations:* Comprehensive diagnostic procedures",
      "*Elderly Care Services:* Specialized care for senior health needs",
      "*Tax Benefits:* Senior-specific tax advantages and HSA options",
      "*Preventive Care:* Age-appropriate health screenings",
      "*Specialist Access:* Geriatricians and elderly care specialists",
      "*Emergency Services:* Priority emergency care for seniors",
    ],
  },
  {
    id: 16,
    title: "Chuks Senior Plus HDPTC",
    cost: 437000,
    period: "year",
    currency: "NGN",
    category: "hdptc",
    description:
      "Premium senior HDPTC with comprehensive coverage, priority healthcare services, intensive care, advanced diagnostics, and extensive chronic illness support",
    detailedCoverage: [
      "*Comprehensive Coverage:* Extensive medical benefits for seniors",
      "*Priority Healthcare Services:* Fast-track access to medical care",
      "*Intensive Care:* ICU services and critical care management",
      "*Advanced Diagnostics:* CT scans, MRI, and specialized tests",
      "*Extensive Chronic Illness Support:* Comprehensive long-term care",
      "*Premium Tax Benefits:* Maximum HSA contributions and deductions",
      "*Specialist Care:* Premium access to geriatric specialists",
      "*Emergency Services:* VIP emergency medical services",
    ],
  },
  // Chuks Gems (Naira)
  {
    id: 17,
    title: "Gems A",
    cost: 12400,
    period: "year",
    currency: "NGN",
    category: "gems",
    description:
      "Entry-level gems plan with basic healthcare coverage, outpatient services, essential diagnostics, and wellness benefits",
    detailedCoverage: [
      "*Basic Healthcare Coverage:* Essential medical services and treatments",
      "*Outpatient Services:* General medical consultations and care",
      "*Essential Diagnostics:* Basic laboratory tests and screenings",
      "*Wellness Benefits:* Preventive care and health promotion",
      "*Emergency Care:* Basic emergency medical services",
      "*Prescription Coverage:* Essential medication benefits",
      "*Preventive Screenings:* Basic health check-ups and monitoring",
      "*Primary Care:* Access to general practitioners and family doctors",
    ],
  },
  {
    id: 18,
    title: "Gems B",
    cost: 15000,
    period: "year",
    currency: "NGN",
    category: "gems",
    description:
      "Mid-tier gems coverage with enhanced outpatient services, diagnostic investigations, minor surgeries, and preventive care",
    detailedCoverage: [
      "*Enhanced Outpatient Services:* Improved medical consultations and care",
      "*Diagnostic Investigations:* Comprehensive laboratory tests and imaging",
      "*Minor Surgeries:* Small surgical procedures and treatments",
      "*Preventive Care:* Enhanced health screenings and wellness programs",
      "*Emergency Services:* Improved emergency medical coverage",
      "*Specialist Consultations:* Access to medical specialists",
      "*Prescription Benefits:* Enhanced medication coverage",
      "*Health Monitoring:* Regular check-ups and health assessments",
    ],
  },
  {
    id: 19,
    title: "Gems C",
    cost: 45000,
    period: "year",
    currency: "NGN",
    category: "gems",
    description:
      "Advanced gems plan with specialist care, comprehensive hospital coverage, intermediate surgeries, and advanced diagnostic services",
    detailedCoverage: [
      "*Specialist Care:* Access to medical specialists and consultants",
      "*Comprehensive Hospital Coverage:* Full inpatient services and care",
      "*Intermediate Surgeries:* Mid-level surgical procedures",
      "*Advanced Diagnostic Services:* Comprehensive medical imaging and tests",
      "*Emergency Care:* Advanced emergency medical services",
      "*Rehabilitation Services:* Physical therapy and recovery programs",
      "*Prescription Coverage:* Comprehensive medication benefits",
      "*Preventive Care:* Advanced health screenings and wellness",
    ],
  },
  {
    id: 20,
    title: "Gems D",
    cost: 120000,
    period: "year",
    currency: "NGN",
    category: "gems",
    description:
      "Premium gems tier with luxury healthcare facilities, personalized services, major surgery coverage, and comprehensive specialist care",
    detailedCoverage: [
      "*Luxury Healthcare Facilities:* Premium medical facilities and amenities",
      "*Personalized Services:* Dedicated healthcare coordination and support",
      "*Major Surgery Coverage:* Comprehensive surgical procedures",
      "*Comprehensive Specialist Care:* Full access to all medical specialists",
      "*VIP Emergency Services:* Priority emergency medical care",
      "*Advanced Diagnostics:* Premium medical imaging and testing",
      "*Concierge Services:* Personalized healthcare assistance",
      "*Wellness Programs:* Premium health and wellness services",
    ],
  },
  {
    id: 21,
    title: "Gems E",
    cost: 220000,
    period: "year",
    currency: "NGN",
    category: "gems",
    description:
      "Elite gems coverage with VIP treatment, exclusive medical centers, advanced procedures, and premium healthcare services",
    detailedCoverage: [
      "*VIP Treatment:* Exclusive and priority medical care",
      "*Exclusive Medical Centers:* Access to premium healthcare facilities",
      "*Advanced Procedures:* Cutting-edge medical treatments and surgeries",
      "*Premium Healthcare Services:* Luxury medical care and amenities",
      "*Elite Emergency Services:* VIP emergency medical response",
      "*Personalized Care Coordination:* Dedicated healthcare management",
      "*Global Healthcare Access:* International medical care options",
      "*Comprehensive Wellness:* Elite health and wellness programs",
    ],
  },
  {
    id: 22,
    title: "Gems F",
    cost: 3000000,
    period: "year",
    currency: "NGN",
    category: "gems",
    description:
      "Ultimate gems plan with world-class healthcare, unlimited coverage benefits, global treatment access, and premium concierge medical services",
    detailedCoverage: [
      "*World-Class Healthcare:* Access to the finest medical facilities globally",
      "*Unlimited Coverage Benefits:* No limits on medical expenses",
      "*Global Treatment Access:* Worldwide medical care and treatments",
      "*Premium Concierge Medical Services:* Personal healthcare coordination",
      "*Ultimate Emergency Services:* Global emergency medical response",
      "*Exclusive Specialist Access:* World-renowned medical specialists",
      "*Luxury Medical Facilities:* Premium healthcare environments",
      "*Comprehensive Global Wellness:* International health and wellness programs",
    ],
  },
  // Diaspora HDPTC (USD)
  {
    id: 23,
    title: "Chuks Basic Diaspora HDPTC",
    cost: 192,
    period: "year",
    currency: "USD",
    category: "diaspora-hdptc",
    description:
      "International HDPTC with tax advantages, global healthcare access, essential coverage, and diaspora-specific benefits",
    detailedCoverage: [
      "*Tax Advantages:* International tax benefits and HSA eligibility",
      "*Global Healthcare Access:* Worldwide medical care coverage",
      "*Essential Coverage:* Basic international medical services",
      "*Diaspora-Specific Benefits:* Tailored coverage for overseas residents",
      "*High Deductible Structure:* Lower premiums with higher deductibles",
      "*Emergency Services:* Global emergency medical assistance",
      "*Preventive Care:* International health screenings and wellness",
      "*Prescription Coverage:* Essential medication benefits worldwide",
    ],
  },
  {
    id: 24,
    title: "Chuks Plus Diaspora HDPTC",
    cost: 244,
    period: "year",
    currency: "USD",
    category: "diaspora-hdptc",
    description:
      "Enhanced diaspora HDPTC with reduced deductibles, premium network access, comprehensive coverage, and international healthcare benefits",
    detailedCoverage: [
      "*Reduced Deductibles:* Lower out-of-pocket costs before coverage",
      "*Premium Network Access:* Access to top-tier international providers",
      "*Comprehensive Coverage:* Enhanced international medical benefits",
      "*International Healthcare Benefits:* Global medical care advantages",
      "*Enhanced Tax Benefits:* Improved HSA contributions and deductions",
      "*Global Emergency Services:* Premium emergency medical assistance",
      "*Specialist Access:* International medical specialists",
      "*Advanced Diagnostics:* Global medical imaging and testing",
    ],
  },
  {
    id: 25,
    title: "Chuks Superior Diaspora HDPTC",
    cost: 262,
    period: "year",
    currency: "USD",
    category: "diaspora-hdptc",
    description:
      "Superior international HDPTC with comprehensive global coverage, advanced healthcare access, and premium diaspora benefits",
    detailedCoverage: [
      "*Comprehensive Global Coverage:* Extensive worldwide medical benefits",
      "*Advanced Healthcare Access:* Premium international medical facilities",
      "*Premium Diaspora Benefits:* Superior coverage for overseas residents",
      "*Superior Tax Advantages:* Maximum HSA benefits and deductions",
      "*Global Specialist Network:* Access to world-class medical specialists",
      "*Advanced Emergency Services:* Superior global emergency care",
      "*Comprehensive Diagnostics:* Advanced international medical testing",
      "*Premium Wellness Programs:* Global health and wellness services",
    ],
  },
  {
    id: 26,
    title: "Chuks Senior Diaspora HDPTC",
    cost: 325,
    period: "year",
    currency: "USD",
    category: "diaspora-hdptc",
    description:
      "Senior-focused international HDPTC with specialized geriatric care worldwide, chronic disease management, and comprehensive elderly healthcare services",
    detailedCoverage: [
      "*Specialized Geriatric Care:* Global elderly-focused medical services",
      "*Chronic Disease Management:* International long-term condition care",
      "*Comprehensive Elderly Healthcare:* Complete senior medical services",
      "*Senior Tax Benefits:* Maximum HSA advantages for seniors",
      "*Global Geriatric Specialists:* Access to elderly care experts worldwide",
      "*Priority Emergency Services:* Senior-focused global emergency care",
      "*Advanced Senior Diagnostics:* Age-appropriate medical testing",
      "*International Wellness Programs:* Global senior health and wellness",
    ],
  },
];
